spring:
  application:
    name: favorite-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/lifestylelogistics?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username : root
    password: Ravikr@123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS:localhost:9092}
server:
  port: 8084
